# Sample Control Service configuration file
# Save this file as /etc/scion/cs.toml
[general]
id = "cs"
config_dir = "/etc/scion"
# reconnect_to_dispatcher = true

[log.console]
level = "info"

[beaconing]
origination_interval = "5s"
propagation_interval = "5s"

[metrics]
prometheus = "127.0.0.1:30454" # change to 0.0.0.0 to access from outside

# [api]
# addr = "0.0.0.0:8080"

[beacon_db]
connection = "/var/lib/scion/control.beacon.db"

[path_db]
connection = "/var/lib/scion/control.path.db"

[trust_db]
connection = "/var/lib/scion/control.trust.db"
